# -*- coding: utf-8 -*-
"""WasteClassifierV2L.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/GarethNobleLFG/recycle-agent/blob/main/model_training/notebooks/WasteClassifierV2L.ipynb

# Load Data

Link to dataset: https://www.kaggle.com/datasets/alistairking/recyclable-and-household-waste-classification
"""

from google.colab import drive
import os

drive.mount('/content/drive')

# Paths
DRIVE_ZIP = '/content/drive/MyDrive/WasteDataset.zip'
DATASET_PATH = '/content/dataset/'
DATASET_ROOT = '/content/dataset/images/images'   # raw source classes
SPLIT_ROOT = '/content/dataset_split'            # output after restructure

os.makedirs(DATASET_PATH, exist_ok=True)

# Commented out IPython magic to ensure Python compatibility.
# Copy zip from Drive and extract
!cp "{DRIVE_ZIP}" "{DATASET_PATH}"
# %cd "{DATASET_PATH}"
!unzip -qq "{os.path.basename(DRIVE_ZIP)}"
# %cd /content

"""### Data loading and preprocessing functions"""

import os
import shutil
import random
import hashlib
import matplotlib.pyplot as plt
import tensorflow as tf
from PIL import Image
from collections import defaultdict


# Filesystem
def explore_dataset_folder(root_path, max_files=3):
    """Recursively prints folder structure, capping files shown per folder."""
    for root, dirs, files in os.walk(root_path):
        level = root.replace(root_path, '').count(os.sep)
        indent = ' ' * 4 * level
        print(f"{indent}[{os.path.basename(root)}/]")
        sub_indent = ' ' * 4 * (level + 1)
        for f in files[:max_files]:
            print(f"{sub_indent}{f}")
        if len(files) > max_files:
            print(f"{sub_indent}... and {len(files) - max_files} more files")


# Hashing
def hash_image(path):
    """Returns an MD5 hash of the image pixel content, normalized to RGB."""
    with Image.open(path) as img:
        return hashlib.md5(img.convert("RGB").tobytes()).hexdigest()


# Raw dataset duplicate check (before splitting)
def check_raw_duplicates(src_root):
    """
    Checks for duplicate images within each class across its subfolders
    (e.g. default/ vs real_world/) in the original unsplit dataset.
    Returns a dict of {class_name: [(path_a, path_b), ...]} for all duplicates found.
    """
    print("Hashing raw dataset...\n")
    all_duplicates = {}
    total_dupes = 0

    for class_name in sorted(os.listdir(src_root)):
        class_path = os.path.join(src_root, class_name)
        if not os.path.isdir(class_path):
            continue

        hash_to_path = {}
        dupes = []

        for subfolder in os.listdir(class_path):
            subfolder_path = os.path.join(class_path, subfolder)
            if not os.path.isdir(subfolder_path):
                continue
            for fname in os.listdir(subfolder_path):
                if not fname.lower().endswith((".png", ".jpg", ".jpeg")):
                    continue
                fpath = os.path.join(subfolder_path, fname)
                try:
                    h = hash_image(fpath)
                    if h in hash_to_path:
                        dupes.append((hash_to_path[h], fpath))
                    else:
                        hash_to_path[h] = fpath
                except Exception as e:
                    print(f"  Skipping {fpath}: {e}")

        if dupes:
            all_duplicates[class_name] = dupes
            total_dupes += len(dupes)
            print(f"  [{class_name}]: {len(dupes)} duplicate(s)")

    print(f"\n=== Summary ===")
    if total_dupes == 0:
        print("No duplicates found in raw dataset.")
    else:
        print(f"Found {total_dupes} duplicate image(s) across {len(all_duplicates)} class(es).")
        print("These will be removed during restructure_dataset().")

    return all_duplicates


def plot_raw_duplicates(all_duplicates, num_examples=5):
    """
    Plots duplicate image pairs found in the raw dataset side by side.

    Args:
        all_duplicates: dict returned by check_raw_duplicates()
        num_examples:   max number of pairs to plot
    """
    pairs = []
    for class_name, dupes in all_duplicates.items():
        for path_a, path_b in dupes:
            pairs.append((class_name, path_a, path_b))
            if len(pairs) >= num_examples:
                break
        if len(pairs) >= num_examples:
            break

    if not pairs:
        print("No duplicates to plot.")
        return

    fig, axes = plt.subplots(len(pairs), 2, figsize=(6, 3 * len(pairs)))
    fig.suptitle("Duplicate Images in Raw Dataset", fontsize=14, fontweight="bold", y=1.01)

    if len(pairs) == 1:
        axes = [axes]

    for i, (class_name, path_a, path_b) in enumerate(pairs):
        for ax, path, subfolder_label in zip(
            axes[i],
            [path_a, path_b],
            [os.path.basename(os.path.dirname(path_a)),
             os.path.basename(os.path.dirname(path_b))]
        ):
            ax.imshow(Image.open(path).convert("RGB"))
            ax.axis("off")
            ax.set_title(
                f"[{class_name}]\n{subfolder_label}\n{os.path.basename(path)}",
                fontsize=8
            )

    plt.tight_layout()
    plt.show()


# Restructure and deduplicate dataset
def restructure_dataset(src_root, dst_root, train=0.8, val=0.1, test=0.1, seed=42):
    """
    Converts:
        src_root/{class_name}/{subfolder}/images...
    Into:
        dst_root/train/{class_name}/images...
        dst_root/val/{class_name}/images...
        dst_root/test/{class_name}/images...

    Deduplicates globally across all classes before splitting, so identical
    images (even across classes) always land in the same split.
    """
    assert abs(train + val + test - 1.0) < 1e-6, "Splits must sum to 1.0"
    random.seed(seed)

    print("Hashing all images for global deduplication...")
    global_seen   = {}  # {hash: (class_name, path)}
    class_buckets = defaultdict(list)  # {class_name: [unique paths]}

    for class_name in sorted(os.listdir(src_root)):
        class_path = os.path.join(src_root, class_name)
        if not os.path.isdir(class_path):
            continue
        for subfolder in os.listdir(class_path):
            subfolder_path = os.path.join(class_path, subfolder)
            if not os.path.isdir(subfolder_path):
                continue
            for fname in os.listdir(subfolder_path):
                if not fname.lower().endswith((".png", ".jpg", ".jpeg")):
                    continue
                fpath = os.path.join(subfolder_path, fname)
                try:
                    h = hash_image(fpath)
                    if h in global_seen:
                        continue  # skip global duplicate
                    global_seen[h] = (class_name, fpath)
                    class_buckets[class_name].append(fpath)
                except Exception as e:
                    print(f"  Skipping {fpath}: {e}")

    print(f"Found {len(global_seen)} unique images across {len(class_buckets)} classes.\n")

    for class_name, images in class_buckets.items():
        random.shuffle(images)
        n       = len(images)
        n_train = int(n * train)
        n_val   = int(n * val)

        splits = {
            "train": images[:n_train],
            "val":   images[n_train:n_train + n_val],
            "test":  images[n_train + n_val:]
        }

        counts = {}
        for split_name, files in splits.items():
            out_dir = os.path.join(dst_root, split_name, class_name)
            os.makedirs(out_dir, exist_ok=True)
            for src_path in files:
                subfolder = os.path.basename(os.path.dirname(src_path))
                fname     = f"{subfolder}_{os.path.basename(src_path)}"
                shutil.copy(src_path, os.path.join(out_dir, fname))
            counts[split_name] = len(files)

        print(f"  {class_name}: {counts['train']} train | {counts['val']} val | {counts['test']} test  ({n} unique)")


# Leakage check on split dataset
def check_leakage_by_hash(dataset_root):
    """
    Checks for data leakage across train/val/test splits by comparing MD5
    hashes. Catches duplicates even if they have different filenames.
    """
    splits = ["train", "val", "test"]
    print("Hashing split dataset...\n")

    split_hashes = {}
    for split in splits:
        split_hashes[split] = {}
        split_dir = os.path.join(dataset_root, split)
        for class_name in sorted(os.listdir(split_dir)):
            class_dir = os.path.join(split_dir, class_name)
            if not os.path.isdir(class_dir):
                continue
            for fname in os.listdir(class_dir):
                fpath = os.path.join(class_dir, fname)
                try:
                    h = hash_image(fpath)
                    split_hashes[split][h] = (class_name, fname)
                except Exception as e:
                    print(f"  Skipping {fpath}: {e}")
        print(f"  {split}: {len(split_hashes[split])} unique images")

    pairs         = [("train", "val"), ("train", "test"), ("val", "test")]
    leakage_found = False

    for split_a, split_b in pairs:
        overlap = set(split_hashes[split_a]) & set(split_hashes[split_b])
        print(f"\n--- {split_a} vs {split_b} ---")
        if not overlap:
            print("  No leakage found.")
        else:
            leakage_found = True
            print(f"  WARNING: {len(overlap)} duplicate(s) found:")
            for h in sorted(overlap)[:5]:
                ca, fa = split_hashes[split_a][h]
                cb, fb = split_hashes[split_b][h]
                print(f"    [{ca}] {fa}  ==  [{cb}] {fb}")
            if len(overlap) > 5:
                print(f"    ... and {len(overlap) - 5} more")

    print("\n=== Summary ===")
    if leakage_found:
        print("WARNING: Leakage detected. Re-run restructure_dataset() to fix.")
    else:
        print("No data leakage detected. Splits are clean.")


# Dataloader helpers
def count_images(dataset):
    """Counts total images in a batched tf.data.Dataset."""
    count = 0
    for images, _ in dataset:
        count += images.shape[0]
    return count

"""### Explore raw dataset structure"""

explore_dataset_folder(DATASET_ROOT, max_files=3)

"""### Check Raw Dataset for Duplicates

Before splitting, check for duplicate images between the `default/` and `real_world/`
subfolders within each class. These would cause data leakage if not removed before splitting.
"""

raw_duplicates = check_raw_duplicates(DATASET_ROOT)

plot_raw_duplicates(raw_duplicates, num_examples=5)

"""### Restructure Dataset

Splits the dataset into `train/`, `val/`, and `test/` folders while globally
deduplicating by image hash so no identical image appears in more than one split.
"""

shutil.rmtree(SPLIT_ROOT, ignore_errors=True)  # wipe any previous split
restructure_dataset(
    src_root=DATASET_ROOT,
    dst_root=SPLIT_ROOT,
    train=0.8,
    val=0.1,
    test=0.1,
    seed=42
)

"""### Verify No Data Leakage in Split Dataset"""

check_leakage_by_hash(SPLIT_ROOT)

"""### Create dataloaders"""

IMG_SIZE = (224, 224)
BATCH_SIZE = 32
SEED = 42

# Load train first to extract class_names before prefetch wraps it
_train_base = tf.keras.utils.image_dataset_from_directory(
    os.path.join(SPLIT_ROOT, "train"),
    seed=SEED, image_size=IMG_SIZE, batch_size=BATCH_SIZE, label_mode="categorical"
)

# Get class names
class_names  = _train_base.class_names
idx_to_class = {i: name for i, name in enumerate(class_names)}

# Make the dataloaders
train_dataset = _train_base.prefetch(tf.data.AUTOTUNE)

val_dataset = tf.keras.utils.image_dataset_from_directory(
    os.path.join(SPLIT_ROOT, "val"),
    seed=SEED, image_size=IMG_SIZE, batch_size=BATCH_SIZE, label_mode="categorical"
).prefetch(tf.data.AUTOTUNE)

test_dataset = tf.keras.utils.image_dataset_from_directory(
    os.path.join(SPLIT_ROOT, "test"),
    seed=SEED, image_size=IMG_SIZE, batch_size=BATCH_SIZE, label_mode="categorical"
).prefetch(tf.data.AUTOTUNE)

train_count = count_images(train_dataset)
val_count   = count_images(val_dataset)
test_count  = count_images(test_dataset)
total = train_count + val_count + test_count

print(f"Num classes:   {len(class_names)}")
print(f"Classes:       {class_names}")
print(f"Train images:  {train_count}")
print(f"Val images:    {val_count}")
print(f"Test images:   {test_count}")
print (f"Total images: {total}")

"""## Visualize the data"""

import matplotlib.pyplot as plt
import numpy as np

def show_images(dataset, class_names=None):
    plt.figure(figsize=(8, 8))

    # Take one batch only
    for images, labels in dataset.take(1):
        for i in range(8):
            plt.subplot(3, 3, i + 1)
            plt.imshow(images[i].numpy().astype("uint8"))

            if class_names is not None:
                label_idx = np.argmax(labels[i])
                plt.title(class_names[label_idx])

            plt.axis("off")

    plt.tight_layout()
    plt.show()

show_images(train_dataset, class_names)

"""# Training

## Setup functions for training and eval
"""

import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive
import os
from sklearn.metrics import (
    accuracy_score, precision_score,
    recall_score, f1_score,
    ConfusionMatrixDisplay
)

def plot_loss_acc_training(history):
    """
    Plots training vs. validation accuracy and loss over epochs.

    Args:
        history: Keras History object returned by model.fit()
    """
    accuracy = history.history["accuracy"]
    val_accuracy = history.history["val_accuracy"]
    loss = history.history["loss"]
    val_loss = history.history["val_loss"]
    epochs = range(1, len(accuracy) + 1)

    plt.plot(epochs, accuracy, "bo", label="Training accuracy")
    plt.plot(epochs, val_accuracy, "b", label="Validation accuracy")
    plt.title("Training and validation accuracy")
    plt.legend()
    plt.figure()

    plt.plot(epochs, loss, "bo", label="Training loss")
    plt.plot(epochs, val_loss, "b", label="Validation loss")
    plt.title("Training and validation loss")
    plt.legend()
    plt.show()


def plot_predictions_grid(model, dataset, class_names, num_images=9):
    """
    Displays a grid of images with the model's predicted label and confidence.
    Titles are green for correct predictions and red for incorrect ones.

    Args:
        model:       Trained Keras/TF model
        dataset:     Batched tf.data.Dataset of (image, label) pairs
        class_names: List of class label strings
        num_images:  Number of images to display (default: 9)
    """
    cols = 3
    rows = (num_images + cols - 1) // cols

    images, true_labels = next(iter(
        dataset.unbatch().shuffle(buffer_size=1000).batch(num_images)
    ))

    images = images.numpy()
    true_labels = true_labels.numpy()

    plt.figure(figsize=(cols * 3, rows * 3))

    for i in range(num_images):
        img_array = np.expand_dims(images[i], axis=0)
        predictions = model.predict(img_array, verbose=0)
        predicted_index = np.argmax(predictions[0])
        confidence = np.max(predictions[0]) * 100

        plt.subplot(rows, cols, i + 1)
        plt.imshow(images[i].astype("uint8") if images[i].max() > 1 else images[i], cmap="gray")
        plt.axis("off")

        title = f"{class_names[predicted_index]} ({confidence:.1f}%)"
        true_label_i = int(np.argmax(true_labels[i]))
        color = "green" if predicted_index == true_label_i else "red"
        plt.title(title + f"\n[{class_names[true_label_i]}]", color=color, fontsize=10)

    plt.tight_layout()
    plt.show()


def _get_predictions_and_labels(model, test_dataset):
    """Single-pass collection of predictions and true labels to guarantee alignment."""
    all_preds  = []
    all_labels = []
    for images, labels in test_dataset:
        all_preds.append(model.predict_on_batch(images))
        all_labels.append(labels.numpy())
    predicted = np.argmax(np.concatenate(all_preds,  axis=0), axis=1)
    actual    = np.argmax(np.concatenate(all_labels, axis=0), axis=1)
    return predicted, actual


def evaluate_metrics(model, test_dataset):
    """
    Prints and returns Loss, Accuracy, Precision, Recall, and F1-Score.

    Args:
        model:        Trained Keras/TF model
        test_dataset: Batched tf.data.Dataset of (image, label) pairs
    """
    predicted_i, actual = _get_predictions_and_labels(model, test_dataset)
    test_loss, _        = model.evaluate(test_dataset, verbose=0)

    accuracy  = accuracy_score(actual, predicted_i)
    precision = precision_score(actual, predicted_i, average="weighted")
    recall    = recall_score(actual, predicted_i, average="weighted")
    f1        = f1_score(actual, predicted_i, average="weighted")

    print(f"Loss:      {test_loss:.4f}")
    print(f"Accuracy:  {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall:    {recall:.4f}")
    print(f"F1-Score:  {f1:.4f}")

    return {"loss": test_loss, "accuracy": accuracy, "precision": precision, "recall": recall, "f1": f1}


def plot_confusion_matrix(model, test_dataset, class_names):
    """
    Displays a confusion matrix for the model's predictions.

    Args:
        model:        Trained Keras/TF model
        test_dataset: Batched tf.data.Dataset of (image, label) pairs
        class_names:  List of class label strings
    """
    predicted_i, actual = _get_predictions_and_labels(model, test_dataset)

    fig, ax = plt.subplots(figsize=(10, 10))
    ConfusionMatrixDisplay.from_predictions(
        actual,
        predicted_i,
        ax=ax,
        display_labels=class_names
    )
    plt.xticks(rotation=90)
    plt.title("Confusion Matrix")
    plt.show()


def save_model_to_drive(model, filename, drive_path="MyDrive/WasteClassifierModels"):
    """
    Mounts Google Drive and saves a trained Keras model to it.

    Args:
        model:      Trained Keras/TF model
        filename:   Name of the saved model file (e.g. "model.keras")
        drive_path: Folder path within Google Drive (default: "My Drive/models")
    """
    drive.mount("/content/drive", force_remount=False)

    save_dir = f"/content/drive/{drive_path}"
    os.makedirs(save_dir, exist_ok=True)

    full_path = f"{save_dir}/{filename}"
    model.save(full_path)
    print(f"Model saved to: {full_path}")


def load_model_from_drive(filename, drive_path="MyDrive/WasteClassifierModels"):
    """
    Mounts Google Drive and loads a Keras model from it.

    Args:
        filename:   Name of the saved model file (e.g. "model.keras")
        drive_path: Folder path within Google Drive (default: "My Drive/models")

    Returns:
        Loaded Keras model
    """
    drive.mount("/content/drive", force_remount=False)

    full_path = f"/content/drive/{drive_path}/{filename}"

    if not os.path.exists(full_path):
        raise FileNotFoundError(f"No model found at: {full_path}")

    model = keras.models.load_model(full_path)
    print(f"Model loaded from: {full_path}")
    return model

"""## Create the small model"""

from tensorflow import keras
from tensorflow.keras import layers

inputs = keras.Input(shape=(IMG_SIZE + (3,)))
x = layers.Rescaling(1./255)(inputs)
x = layers.Conv2D(filters=32, kernel_size=3, activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=64, kernel_size=3, activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=128, kernel_size=3, activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=256, kernel_size=3, activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=256, kernel_size=3, activation="relu")(x)
x = layers.Flatten()(x)
outputs = layers.Dense(len(class_names), activation="softmax")(x)

model = keras.Model(inputs=inputs, outputs=outputs)

model.summary()

"""### Compile and train"""

# Choose loss function, optimizer, and metrics
model.compile(loss="categorical_crossentropy", optimizer="rmsprop", metrics=["accuracy"])

# Callback function to save best model during training
callbacks = [
    keras.callbacks.ModelCheckpoint(
        filepath="model.keras",
        save_best_only=True,
        monitor="val_loss"
    ),
    keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=5,
        restore_best_weights=True
    ),
]

# Train the model without augmentation
history = model.fit(
    train_dataset,
    epochs=30,
    validation_data=val_dataset,
    callbacks=callbacks
)

"""### Display loss curve"""

plot_loss_acc_training(history)

"""### Save the model"""

save_model_to_drive(model, "model.keras", drive_path="MyDrive/WasteClassifierModels")

"""### Load the model (if needed)"""

model = load_model_from_drive("model.keras")

"""### Evaluate the model"""

evaluate_metrics(model, test_dataset)

plot_confusion_matrix(model, test_dataset, class_names)

"""### Plot images with model predictions vs. actual labels"""

plot_predictions_grid(model, test_dataset, class_names, num_images=9)

"""## Create data augmented model"""

from tensorflow import keras
from tensorflow.keras import layers

data_augmentation = keras.Sequential(
    [
     layers.RandomFlip("horizontal"),
     layers.RandomRotation(0.1),
     layers.RandomZoom(0.2),
    ]
)

"""Add augmentation layer and dropout layers"""

from tensorflow import keras
from tensorflow.keras import layers

inputs = keras.Input(shape=(IMG_SIZE + (3,)))
x = data_augmentation(inputs)
x = layers.Rescaling(1./255)(x)
x = layers.Conv2D(filters=32, kernel_size=3, activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=64, kernel_size=3, activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=128, kernel_size=3, activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=256, kernel_size=3, activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=256, kernel_size=3, activation="relu")(x)
x = layers.Flatten()(x)
x = layers.Dropout(0.2)(x)
outputs = layers.Dense(len(class_names), activation="softmax")(x)

augmented_model = keras.Model(inputs=inputs, outputs=outputs)

augmented_model.summary()

"""### Compile and train"""

# Choose loss function, optimizer, and metrics
augmented_model.compile(loss="categorical_crossentropy", optimizer="rmsprop", metrics=["accuracy"])

# Callback function to save best model during training
callbacks = [
    keras.callbacks.ModelCheckpoint(
        filepath="augmented_model.keras",
        save_best_only=True,
        monitor="val_loss"
    ),
    keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=40,
        restore_best_weights=True
    ),
]

# Train the model with augmentation
history = augmented_model.fit(
    train_dataset,
    epochs=100,
    validation_data=val_dataset,
    callbacks=callbacks
)

"""### Display loss curve"""

plot_loss_acc_training(history)

"""### Save the model"""

save_model_to_drive(augmented_model, "augmented_model.keras", drive_path="MyDrive/WasteClassifierModels")

"""### Load the model (if needed)"""

augmented_model = load_model_from_drive("augmented_model.keras")

"""### Evaluate the model"""

evaluate_metrics(augmented_model, test_dataset)

plot_confusion_matrix(augmented_model, test_dataset, class_names)

"""## Create Model on EfficientNetV2L"""

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.applications import EfficientNetV2L
data_augmentation = keras.Sequential(
    [
     layers.RandomFlip("horizontal"),
     layers.RandomRotation(0.1),
     layers.RandomZoom(0.2),
    ]
)

"""Create EfficientNetV2L"""

eff_model = EfficientNetV2L(
    include_top=False,
    weights="imagenet",
    pooling="avg",
    input_shape=(IMG_SIZE + (3,)),
    include_preprocessing=True
)

#Layers
inputs = keras.Input(shape=(IMG_SIZE + (3,)))
x = data_augmentation(inputs)
x = eff_model(x)
x = layers.Dropout(0.2)(x)
outputs = layers.Dense(len(class_names), activation="softmax")(x)
eff_net_model = keras.Model(inputs=inputs, outputs=outputs)

#View Layers
eff_net_model.summary()

# Choose loss function, optimizer, and metrics
eff_net_model.compile(loss="categorical_crossentropy", optimizer="rmsprop", metrics=["accuracy"])

# Callback function to save best model during training
callbacks = [
    keras.callbacks.ModelCheckpoint(
        filepath="EfficientNetV2L.keras",
        save_best_only=True,
        monitor="val_loss"
    ),
    keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=5,
        restore_best_weights=True
    ),
]

#Start Training
#I cut batch-size to 8, did not appear to handle 32 well.
history = eff_net_model.fit(
    train_dataset,
    epochs=15,
    validation_data=val_dataset,
    callbacks=callbacks
)

"""### Save the model"""

save_model_to_drive(eff_net_model, "EfficientNetV2L.keras", drive_path="MyDrive/WasteClassifierModels")

"""### Load the model (if needed)"""

eff_net_model = load_model_from_drive("EfficientNetV2L.keras")

"""### Evaluate the model"""

evaluate_metrics(eff_net_model, test_dataset)

"""Confusion Matrix"""

plot_confusion_matrix(eff_net_model, test_dataset, class_names)

"""Plot Loss"""

plot_loss_acc_training(history)

"""### Plot images with model predictions vs. actual labels"""

plot_predictions_grid(eff_net_model, test_dataset, class_names, num_images=9)